[package]
name = "premix-actix"
version = "0.1.0"
edition = "2024"
description = "Actix-web helpers for Premix ORM."
license = "MIT"

[dependencies]
actix-web = "4"
premix-orm = { path = "../premix-orm" }
sqlx = { version = "0.8", default-features = false }
